// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDJmt5OZISfmOH902nroBoa26ep9l4GPQ',
    appId: '1:895055662934:web:d95a9a562b4a10d9de90f7',
    messagingSenderId: '895055662934',
    projectId: 'debateflow-14ce8',
    authDomain: 'debateflow-14ce8.firebaseapp.com',
    databaseURL: 'https://debateflow-14ce8-default-rtdb.firebaseio.com',
    storageBucket: 'debateflow-14ce8.firebasestorage.app',
    measurementId: 'G-RS6VX0JTB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJ4zQ1u5n-T_AQVtAnydPUeZyhrRQ5EQ',
    appId: '1:895055662934:android:52a2352e005cd505de90f7',
    messagingSenderId: '895055662934',
    projectId: 'debateflow-14ce8',
    databaseURL: 'https://debateflow-14ce8-default-rtdb.firebaseio.com',
    storageBucket: 'debateflow-14ce8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZTa17jtYETxsTRoWMVo9j45tkDfCkdE',
    appId: '1:895055662934:ios:fdc90dd06c4cddb7de90f7',
    messagingSenderId: '895055662934',
    projectId: 'debateflow-14ce8',
    databaseURL: 'https://debateflow-14ce8-default-rtdb.firebaseio.com',
    storageBucket: 'debateflow-14ce8.firebasestorage.app',
    iosBundleId: 'com.example.debateflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZTa17jtYETxsTRoWMVo9j45tkDfCkdE',
    appId: '1:895055662934:ios:fdc90dd06c4cddb7de90f7',
    messagingSenderId: '895055662934',
    projectId: 'debateflow-14ce8',
    databaseURL: 'https://debateflow-14ce8-default-rtdb.firebaseio.com',
    storageBucket: 'debateflow-14ce8.firebasestorage.app',
    iosBundleId: 'com.example.debateflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDJmt5OZISfmOH902nroBoa26ep9l4GPQ',
    appId: '1:895055662934:web:d45c397046ac4696de90f7',
    messagingSenderId: '895055662934',
    projectId: 'debateflow-14ce8',
    authDomain: 'debateflow-14ce8.firebaseapp.com',
    databaseURL: 'https://debateflow-14ce8-default-rtdb.firebaseio.com',
    storageBucket: 'debateflow-14ce8.firebasestorage.app',
    measurementId: 'G-CF1S8JG6HQ',
  );

}